name: commitlint-gh-action
author: person93
description: Run commitlint (https://commitlint.js.org/)
runs:
  using: node12
  main: dist/index.js
inputs:
  token:
    description: A token for the repo. Only needs read access.
    required: false
    default: ${{ github.token }}
branding:
  icon: git-commit
  color: gray-dark
